import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = Split("""
""")

if GetDepend('RT_USING_PIN'):
    src += ['drv_gpio.c']

if GetDepend(['RT_USING_SERIAL', 'BSP_USING_UART']):
    src += ['drv_usart.c']

path = [cwd]


group = DefineGroup('ch32v10x_lib', src, depend = [''], CPPPATH = path)

Return('group')
