Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drivers.
src = Split("""
board.c
""")


if GetDepend(['BSP_USING_TCD1209']):
    src += ['drv_tcd1209.c']

if GetDepend(['BSP_USING_CAN']):
    src += ['drv_can.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
