import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

#ch32v10x_adc.c
#ch32v10x_bkp.c
#ch32v10x_crc.c
#ch32v10x_dbgmcu.c
#ch32v10x_dma.c
#ch32v10x_exti.c
#ch32v10x_flash.c
#ch32v10x_gpio.c
#ch32v10x_i2c.c
#ch32v10x_iwdg.c
#ch32v10x_misc.c
#ch32v10x_pwr.c
#ch32v10x_rcc.c
#ch32v10x_rtc.c
#ch32v10x_spi.c
#ch32v10x_tim.c
#ch32v10x_wwdg.c

src = Split("""
ch32v10x_exti.c
ch32v10x_misc.c
ch32v10x_rcc.c
ch32v10x_gpio.c
""")

if GetDepend(['BSP_USING_UART']):
    src += ['ch32v10x_usart.c']

path = [cwd]

group = DefineGroup('ch32v10x_lib', src, depend = [''], CPPPATH = path)

Return('group')
